// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3aUQSJV1CCudqMBHZe3gIjASGeNvXLxM',
    appId: '1:982265954065:web:12792f235d2edac73256b0',
    messagingSenderId: '982265954065',
    projectId: 'intern-57030',
    authDomain: 'intern-57030.firebaseapp.com',
    storageBucket: 'intern-57030.appspot.com',
    measurementId: 'G-CEQQKERTKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDee8z9Bjd7fmBjgmSPazerx_5Hu5x9NCE',
    appId: '1:982265954065:android:00500c0315365bde3256b0',
    messagingSenderId: '982265954065',
    projectId: 'intern-57030',
    storageBucket: 'intern-57030.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoLnXlYfSiKd6Sc1uDyGiYfhPJ5oxASzg',
    appId: '1:982265954065:ios:033a16b2a6b082d53256b0',
    messagingSenderId: '982265954065',
    projectId: 'intern-57030',
    storageBucket: 'intern-57030.appspot.com',
    iosClientId: '982265954065-05qe1t9pmna0eacu7si93sb8kgr6lhk4.apps.googleusercontent.com',
    iosBundleId: 'com.mine.intern',
  );
}
